### ISSUE TITLE
Support for Ryujinx perhaps?

### ISSUE THREAD

**Issue by NeuroticNinjah** [vasilvestre/totk-mod-manager-for-yuzu#16]
Hey is there any chance we can get support for Ryujinx as well. I'm not sure how hard that would be but it would be awesome considering Ryujinx doesn't even have any kind of built in features in their emulator to even enable/disable mods while Yuzu does. It would be much appreciated.

**Comment by vasilvestre** [comment]
> Hey is there any chance we can get support for Ryujinx as well. I'm not sure how hard that would be but it would be awesome considering Ryujinx doesn't even have any kind of built in features in their emulator to even enable/disable mods while Yuzu does. It would be much appreciated.

Ok I will work on this, not right as we try to support more mods and it's extra work :)

**Comment by NeuroticNinjah** [comment]
That looks awesome. I will definitely be keeping a watch on this in the future.

**Comment by vasilvestre** [comment]
> That looks awesome. My only question is will this mod manager in general support local mods in each emulator's respective folder? Regardless I will definitely be keeping a watch on this in the future. 

Yes, I will fetch local mod per emulator, they will display the same screen but the content depends of the emulator

**Comment by NeuroticNinjah** [comment]
That will be awesome. I hope It’s not too hard of a challenge in regards to each emulator since they have different file structures. I wish you the best of luck my friend!

**Comment by vasilvestre** [comment]
Working on linux, feel free to reopen if you have issues. You can also come to the discord for direct help
