### ISSUE TITLE
"could not fetch local mods"

### ISSUE THREAD

**Issue by allek05** [vasilvestre/totk-mod-manager-for-yuzu#22]
Could not fetch local mods after locating the Yuzu folder.
A clear and concise description of the bug is needed.

To Reproduce

    I performed a full install using the tutorial found here: [link](https://tauri.app/v1/guides/getting-started/prerequisites/), and from your page with no issues.
    After launching Zelda.Tears.of.the.Kingdom.Mod.Manager.exe, I selected Yuzu and chose either C:\Yuzu Switch Emulator for PC - Sin or C:\Yuzu Switch Emulator for PC - Sin\Yuzu Early Access.
    Then, I encountered the error message "Could not fetch local mods." I also attempted to use different folders within Yuzu, but none of them worked.
    Please assist.

Screenshots
![image](https://github.com/vasilvestre/totk-mod-manager-for-yuzu/assets/44872339/996864e5-e79b-4f71-862f-8b26d22b036b)
![image](https://github.com/vasilvestre/totk-mod-manager-for-yuzu/assets/44872339/d63ebd87-1c18-4df3-beea-f153c7b6c918)
![image](https://github.com/vasilvestre/totk-mod-manager-for-yuzu/assets/44872339/bb361c52-534d-48bb-91b7-45975027c96d)

Windows 10, latest version, everything is updated.

**Comment by vasilvestre** [comment]
Can you check if the Yuzu folder you selected contains the subfolder "load"? This is the one you should select

**Comment by allek05** [comment]
it worked when i chose the folder "user"
and thank you for help

**Comment by allek05** [comment]
> it worked when i chose the folder "user" and thank you for help

can you make the manager not so bright/darkmode also, my eyes hurt

**Comment by vasilvestre** [comment]
> 

Copy that :)
